{% set name = "igwn-alert" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1c67cd0c1856125acc952f2d151b5f87d919bf68395291df02c48c2b5ab3f1a8
  patches:
    # update requirements
    - 0001-clean-up-requirements.patch

build:
  entry_points:
    - igwn-alert=igwn_alert.tool:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - adc-streaming >=2.3.0
    - hop-client >=0.7.0
    - pyopenssl >=23.0.0
    - python >=3.6
    - python-confluent-kafka >=2.0.0
    - safe-netrc

test:
  requires:
    - pip
    - pytest
  commands:
    # check requirements
    - python -m pip check igwn-alert
    - python -m pip show igwn-alert
    # run test suite
    - python -m pytest --pyargs igwn_alert.tests -ra -v
    # check entry points
    - igwn-alert --help

about:
  home: https://igwn-alert.readthedocs.io/
  dev_url: https://git.ligo.org/computing/igwn-alert/client.git
  doc_url: https://igwn-alert.readthedocs.io/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: IGWN Alert Network
  description: |
    The IGWN Alert System (LVAlert) is a prototype notification service
    built on Apache Kafka, using the publish-subscribe (pubsub) protocol.
    It is a higher-level modification of [SCIMMA](https://scimma.org/)’s
    [hop-client](https://hop-client.readthedocs.io/) to streamline
    receiving and responding to alerts from
    [GraceDB](https://gracedb.ligo.org).

extra:
  recipe-maintainers:
    - aepace
    - duncanmmacleod
